# ─────────────────────────────────────────────
# Configuración de la aplicación
# ─────────────────────────────────────────────
spring.application.name=biblioteca-api

# ─────────────────────────────────────────────
# Conexión a MongoDB Atlas
# Reemplaza la URI con tu cadena de conexión real
# obtenida en el Paso 5 de la sección MongoDB Atlas
# ─────────────────────────────────────────────
spring.data.mongodb.uri=mongodb+srv://adminBiblioteca:Biblio2024!@biblioteca-cluster.qz9belm.mongodb.net/biblioteca_db?retryWrites=true&w=majority&appName=biblioteca-cluster

# Nombre de la base de datos en MongoDB
spring.data.mongodb.database=biblioteca_db

# ─────────────────────────────────────────────
# Servidor
# ─────────────────────────────────────────────
server.port=8080
